on: [push, pull_request]
name: Deploy Terraform
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.2
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: './terraform'
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.2
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: './terraform'
    # - name: 'Terraform Apply'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.2
    #     tf_actions_subcommand: 'apply'
        # tf_actions_working_dir: './terraform'
